config: {}
description: Default Incus profile
devices:
  eth0:
    name: eth0
    network: incusbr0
    type: nic
  root:
    path: /
    pool: 1stStorage
    type: disk
name: default
used_by:
- /1.0/instances/2404-k3s
- /1.0/instances/9-k3s
- /1.0/instances/2410-containerd
- /1.0/instances/2410-containerd-k8s
- /1.0/instances/2410-containerd-3s-server
project: default
